# Generated by Django 4.2.4 on 2023-08-31 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='cost_currency',
            new_name='price_currency',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='costs',
            new_name='prices',
        ),
    ]
