# Generated by Django 4.2.4 on 2023-08-31 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_cost_prices_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groceries',
            new_name='Grocery',
        ),
    ]
